config/routes.rb
Rails.application.routes.draw do
  resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'sessions/new'
  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts
  root 'static_pages#home'
  resources :relationships, only: [:create, :destroy]
  get  '/login',  to: 'sessions#new'
  post  '/login',  to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A Sample Reddit app by Sidharth bansal
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", home_path  %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<section class="navigation">
<div class="nav-container">
<div class="brand" id="logo">
  <%= link_to "Microreddit", root_url %>
</div>
<nav>
  <div class="nav-mobile"><a id="nav-toggle" href="#!"><span></span></a></div>
  <ul class="nav-list">
    <li>
      <%= link_to "Home", home_path %>
    </li>
    <li>
      <%= link_to "Help", help_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li>
          <a href="#!">Account</a>
          <ul class="nav-dropdown">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class = "divider"></li>
            <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
  </ul>
</nav>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Microreddit</title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

<article>
  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
    <%= yield %>
  </article>
  </body>

<%= render 'layouts/footer' %>
</html>